CREATE TABLE activity_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    action      VARCHAR(100)                            NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT pk_activity_logs PRIMARY KEY (id)
);

CREATE TABLE camp_sessions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    start_date  date                                    NOT NULL,
    end_date    date                                    NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_camp_sessions PRIMARY KEY (id)
);

CREATE TABLE children
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    birth_date date                                    NOT NULL,
    parent_id  BIGINT,
    CONSTRAINT pk_children PRIMARY KEY (id)
);

CREATE TABLE duty_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        date                                    NOT NULL,
    employee_id BIGINT,
    session_id  BIGINT,
    report      VARCHAR(2000)                           NOT NULL,
    CONSTRAINT pk_duty_logs PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name VARCHAR(255)                            NOT NULL,
    position  VARCHAR(255)                            NOT NULL,
    user_id   BIGINT,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE medical_cards
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    child_id         BIGINT,
    health_info      VARCHAR(1000),
    chronic_diseases VARCHAR(500),
    allergies        VARCHAR(500),
    vaccinations     VARCHAR(500),
    notes            VARCHAR(1000),
    CONSTRAINT pk_medical_cards PRIMARY KEY (id)
);

CREATE TABLE medical_visits
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            date                                    NOT NULL,
    child_id        BIGINT,
    doctor_id       BIGINT,
    description     VARCHAR(1000),
    recommendations VARCHAR(1000),
    medications     VARCHAR(500),
    CONSTRAINT pk_medical_visits PRIMARY KEY (id)
);

CREATE TABLE menus
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date                                    NOT NULL,
    session_id BIGINT,
    breakfast  VARCHAR(1000),
    lunch      VARCHAR(1000),
    dinner     VARCHAR(1000),
    notes      VARCHAR(1000),
    CONSTRAINT pk_menus PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipient_id BIGINT,
    type         VARCHAR(50)                             NOT NULL,
    subject      VARCHAR(200)                            NOT NULL,
    message      VARCHAR(2000)                           NOT NULL,
    status       VARCHAR(30)                             NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    sent_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id  BIGINT,
    voucher_id BIGINT,
    amount     DOUBLE PRECISION                        NOT NULL,
    date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(30)                             NOT NULL,
    method     VARCHAR(30),
    comment    VARCHAR(500),
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE schedules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        date                                    NOT NULL,
    session_id  BIGINT,
    employee_id BIGINT,
    time        time WITHOUT TIME ZONE                  NOT NULL,
    event_type  VARCHAR(100)                            NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT pk_schedules PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username             VARCHAR(255)                            NOT NULL,
    password             VARCHAR(255)                            NOT NULL,
    email                VARCHAR(255)                            NOT NULL,
    role                 VARCHAR(255)                            NOT NULL,
    user_type            VARCHAR(255)                            NOT NULL,
    email_notifications  BOOLEAN                                 NOT NULL DEFAULT TRUE,
    sms_notifications    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    theme                VARCHAR(10)                             NOT NULL DEFAULT 'auto',
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vouchers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    child_id     BIGINT,
    session_id   BIGINT,
    status       VARCHAR(255),
    booking_date date,
    CONSTRAINT pk_vouchers PRIMARY KEY (id)
);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_user UNIQUE (user_id);

ALTER TABLE medical_cards
    ADD CONSTRAINT uc_medical_cards_child UNIQUE (child_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE activity_logs
    ADD CONSTRAINT FK_ACTIVITY_LOGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE children
    ADD CONSTRAINT FK_CHILDREN_ON_PARENT FOREIGN KEY (parent_id) REFERENCES users (id);

ALTER TABLE duty_logs
    ADD CONSTRAINT FK_DUTY_LOGS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE duty_logs
    ADD CONSTRAINT FK_DUTY_LOGS_ON_SESSION FOREIGN KEY (session_id) REFERENCES camp_sessions (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE medical_cards
    ADD CONSTRAINT FK_MEDICAL_CARDS_ON_CHILD FOREIGN KEY (child_id) REFERENCES children (id);

ALTER TABLE medical_visits
    ADD CONSTRAINT FK_MEDICAL_VISITS_ON_CHILD FOREIGN KEY (child_id) REFERENCES children (id);

ALTER TABLE medical_visits
    ADD CONSTRAINT FK_MEDICAL_VISITS_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES employees (id);

ALTER TABLE menus
    ADD CONSTRAINT FK_MENUS_ON_SESSION FOREIGN KEY (session_id) REFERENCES camp_sessions (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_PARENT FOREIGN KEY (parent_id) REFERENCES users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_VOUCHER FOREIGN KEY (voucher_id) REFERENCES vouchers (id);

ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_SESSION FOREIGN KEY (session_id) REFERENCES camp_sessions (id);

ALTER TABLE vouchers
    ADD CONSTRAINT FK_VOUCHERS_ON_CHILD FOREIGN KEY (child_id) REFERENCES children (id);

ALTER TABLE vouchers
    ADD CONSTRAINT FK_VOUCHERS_ON_SESSION FOREIGN KEY (session_id) REFERENCES camp_sessions (id);